HW-nodeJs-02
StudentVlad5/nodejs-homework-goit-rest-api pull request #1
Opened 2023-01-25 17:35 UTC by StudentVlad5

Hello.
Please check my code for task 2 - Node JS
Thanks.

2023-01-25 19:30 UTC, Eastvarga requested changes
Багато зауважень

2023-01-25 19:30 UTC, Eastvarga commented on models/contacts.js
> +  data[index] = { ...body, id: contactId };
не вірно, це не апдейт старого контакту - це заміна його тим що містить body, а якщо у body немає поля телефона, то в контакта воно зникне, Ви хочаб перевіряйте дію свого коду.

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +  phone: Joi.string()
чому телефон не необхідне поле?

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +  email: Joi.string().email({
теж саме, чому не необхідне?

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +const schema = Joi.object({
Схему валідації варто окремо винести в інший модуль

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +    return res.json({
Де статус помилки res.status(404).json(body) ?

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +  const validationResult = schema.validate(req.query);
Валідацію треба винести до окремого мідлвару

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +  if (name && email && phone) {
це не потрібна дикість =) Навіщо валідація тоді?

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +    return res.json({
Де сет статусу відповіді?

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +  if (!name || !email || !phone) {
Це питання валідації все дає Вам схема валідації та її валідація, розберіться с Джой

2023-01-25 19:30 UTC, Eastvarga commented on routes/api/contacts.js
> +  const validationResult = schema.validate(req.query);
Винести у окремий мідлвар, валідацію

2023-01-26 04:22 UTC, StudentVlad5 commented on models/contacts.js
> +  data[index] = { ...body, id: contactId };
перевірка body вже відбувається на роутері
router.put("/:contactId", async (req, res, next) => {
  const { name, email, phone } = req.query;
всі перевірки проводяться в єдиному місці в файлі routes/api/contacts.js 
наприклад, якщо додадуть до body додаткові дані : дату народження, вік, стать і тд, то перевірка на наявність/валідацію проведеться  один раз, і не потрібно пам'ятати, що потрібно дублювати перевірку в іншому файлі.
 
  якщо буде відсутнє поле, то отримаємо помилку"status": 400,
    "message": "missing fields" , і функія updateContact не запуститься

2023-01-26 04:25 UTC, StudentVlad5 commented on routes/api/contacts.js
> +  phone: Joi.string()
перевірка на поле "телефон" відбувається до старту валідації окремою умовою
  if (!name || !email || !phone) {
    return res.json({
      status: 400,
      message: "missing fields",
    });

2023-01-26 04:27 UTC, StudentVlad5 commented on routes/api/contacts.js
> +  email: Joi.string().email({
перевірка на поле "email" відбувається до старту валідації окремою умовою
if (!name || !email || !phone) {
return res.json({
status: 400,
message: "missing fields",
});

Додав до валідації всім полям параметр required()

2023-01-26 04:28 UTC, StudentVlad5 commented on routes/api/contacts.js
> +const schema = Joi.object({
Дякую. Виніс в окремий модуль.

2023-01-26 04:49 UTC, StudentVlad5 commented on routes/api/contacts.js
> +    return res.json({
статус помилка/успіх передавав в самому .json({ status: 400, message: validationResult.error });
в матеріалах/лекціях бачу приклади з res.status(404).json(body),  а також багато прикладів з res.json({ status: 400, body });
змінив на res.status(404).json(body). дякую за коментар: пошукаю інфо в чому різниця передачі статусів

2023-01-26 04:49 UTC, StudentVlad5 commented on routes/api/contacts.js
> +  const validationResult = schema.validate(req.query);
Дякую. Виніс в окремий модуль

2023-01-26 05:09 UTC, StudentVlad5 commented on routes/api/contacts.js
> +  if (name && email && phone) {
погоджусь з коментарем на 100%, але умови такої перевірки прописані в ДЗ, крок 2 (цитую пункти нижче по тексту) 
сама валідація вказана 3 кроком, а при відсутності поля потрібно зробити response з іншим "message"

"Если в body нет каких-то обязательных полей, возвращает json с ключом {"message": "missing required name field"} и статусом 400

Получает body в json-формате c обновлением любых полей name, email и phone
Если body нет, возвращает json с ключом {"message": "missing fields"} и статусом 400"

2023-01-26 05:10 UTC, StudentVlad5 commented on routes/api/contacts.js
> +    return res.json({
додав  res.status(201).json(body)

2023-01-26 05:11 UTC, StudentVlad5 commented on routes/api/contacts.js
> +  if (!name || !email || !phone) {
така перевірка передбачена умовами ДЗ

2023-01-26 05:12 UTC, StudentVlad5 commented on routes/api/contacts.js
> +  const validationResult = schema.validate(req.query);
Готово.

2023-01-26 18:10 UTC, Eastvarga commented on models/contacts.js
> +  data[index] = { ...body, id: contactId };
const { name, email, phone } = req.query; Ось це зовсім дивно!
Чи ви прислухаєтесь до того що Вам кажуть? 
Раджу прислухатись, та подумати, перед тим як щось відповідати, бо довго на помилках вчитись будете

2023-01-26 18:16 UTC, Eastvarga commented on routes/api/contacts.js
> +  phone: Joi.string()
Валідація не стартує - валідація йде попереду - вона дозволяє відповідати коректними помилками на некоректні вхідні данні запиту, у кожного запиту є свої валідації. Так валідацію можна перевикористовувати для кожного з раутів, але вона завжди йде мідлваром до контроллера-сервісу з основною бізнес логікою.
Окрема умова - ви поимляєтесь - немає окремих умов - є валідація в котрій вказані усі умови для неї, можна робити ланцюг з валідацій, але не "окрема умова" - не має такого поняття, є валідація тіла\параметрів запиту перед стартом обробки цього запиту

2023-01-26 18:25 UTC, Eastvarga commented on routes/api/contacts.js
> +  email: Joi.string().email({
Будь ласка, Знайдіть у ютубі щось по node.js simple REST API example, почитайте уважно, або подивіться якщо погано розумієте англійську мову, перекладіть статті гуг транслейтом, однак не відповідайте більш так як зараз.
Зараз Ви кажете, що не вказали у схемі валідаціі умову валідації, бо це "окрема умова".
Усі умови до тіла\параметрів запиту це умови валідації (validation - перевірка)

2023-01-26 18:59 UTC, Eastvarga requested changes
Є зауваження, старі деякі залишились не вирішеними

2023-01-26 18:59 UTC, Eastvarga commented on routes/api/contacts.js
> +  return res.status(200).json({
return res.status(200).json(allContacts) буде доцільніше.
Ви повинні розуміти, чому так. Бо технічна інформація успішної відповіді не потрібна у тілі відповіді, вона зазвичай одна й таж =), да і вона є у саммій відповіді - читайте res req що таке та як встановлювати їх технічну інформацію.
Наразі дуже слабкі знання.

2023-01-26 18:59 UTC, Eastvarga commented on routes/api/contacts.js
> +  const validationResult = schema.validate(req.query);
Ні не винисли - читайте матеріал - уся перевірка йде у окремому мідлварі
router.post("/", createUserValidation, createUserRouter); - розумієте послідовність, та де яка логіка?

2023-01-26 18:59 UTC, Eastvarga commented on routes/api/contacts.js
> +  if (name && email && phone) {
Чи Ви вивчали матеріали? Дивились лекції?
По-перше - що таке валідація та навіщо вона потрібна, нажаль, Ви не розібрались.
По-друге - Схему валідації Ви доповнили - тепер спробуйте створити такий запит, котрий призведе до виконання коду
if (name && email && phone) { у цих дужках }
якщо валідацію вірно налаштували - він ніколи не виконаєтся, а отже Ви написали зайвий код що нічого не робить окрім додавання зайвої ваги коду

2023-01-26 18:59 UTC, Eastvarga commented on routes/api/contacts.js
> +  if (!name || !email || !phone) {
Умовами ДЗ передбачена перевірка  - це значить валідація, в ДЗ не вказано що цей код повинен бути у тілі контролера (бізнес логіки), інженер завжди думає з точки зору кращого виконання, чи Ви не дивились лекцій? 
Також не бачу мідлвару валідації, у PUT запиті.

2023-01-26 18:59 UTC, Eastvarga commented on routes/api/contacts.js
> +  const validationResult = schema.validate(req.query);
Де окремий мідлвар, підкажіть, будь ласка? Щось не знайду його, нажаль.

2023-01-26 18:59 UTC, Eastvarga commented on routes/api/contacts.js
>      { name, email, phone }
у данному випадку краще передавати замість { name, email, phone } просто req.body, або body якщо вже отримали його деструктивним присвоєнням

2023-01-26 18:59 UTC, Eastvarga commented on routes/api/contacts.js
>        status: 404,
У тілі запиту не обов'язково дублювати технічну інформацію  -  json({ **status: 404**,   message: "Not found",}) тут достатньо  json({ message: "Not found"})

2023-01-28 18:02 UTC, Eastvarga requested changes

2023-01-28 18:02 UTC, Eastvarga commented on middleware/shemaPut.js
> +});
Для PUT запиту використовується зазвичай уся поля об'єкту - тож схема повинна бути ідентичною до POST схеми,
Для PATCH запиту поля об'екту можуть бути не обов'язковими, але треба у джой додати метод що кине помилку, якщо у тілі запиту не буде жодного з полів

2023-01-28 18:02 UTC, Eastvarga commented on middleware/validationPost.js
> +    }
Приберить ці зайві строки коду з 3 по 6, та розбіріться вже з тим, що робить schema.validate( req.body), Ви вперто не бажаєте вчитись

2023-01-28 18:02 UTC, Eastvarga commented on middleware/validationPut.js
> +    const { name, email, phone } = req.body;
теж саме  const { error } = schema.validate(req.body); цього достатньо щоб у змінній error  були необхідні помилки валідації, якщо коректно написана схема, Вам лише потрібно їх, якщо вони є передати в юзерфрендлі форматі у відповідь на запит

2023-01-28 18:02 UTC, Eastvarga commented on models/contacts.js
> +  data[index] = await { ...data[index], ...body };
дикість - вже хтось таке використовувал - погане не варто наслідувати - з цього запису я бачу що проміси Ви не розумієте
data[index] = { ...data[index], ...body }; - це вірний запис

2023-01-28 18:02 UTC, Eastvarga commented on routes/api/contacts.js
> +  return res.status(200).json({
Погано, що не бачу я розуміння Вами зауваження та виводу з цього приводу

2023-01-28 18:02 UTC, Eastvarga commented on routes/api/contacts.js
> +  const contact = await contactsOperations.addContact({ ...req.body });
розпилення зайве  const contact = await contactsOperations.addContact(req.body); - так можно було зробити

2023-01-29 10:51 UTC, Eastvarga requested changes
Залишилось прибрати зайвий код

2023-01-29 10:51 UTC, Eastvarga commented on middleware/validation.js
> +    }
Зайвий код.
 if (!req.body) {
      return res.status(400).json({ message: "missing fields" });
    }
приберіть його та розберіться з тим що робить
const { error } = schema.validate(req.body);

2023-01-29 19:37 UTC, StudentVlad5 commented on middleware/validation.js
> +    }
Дякую. Прибрав дану перевірку,
В ДЗ в методі PUT вказана умова перевірки саме  body з окремим повідомленням:
"Если body нет, возвращает json с ключом {"message": "missing fields"} и статусом 400"

2023-01-30 17:09 UTC, Eastvarga approved these changes

2023-01-30 17:09 UTC, merged