without unit-test
StudentVlad5/nodejs-homework-goit-rest-api pull request #4
Opened 2023-02-07 17:17 UTC by StudentVlad5

Доброго дня, пане Олександре,
Прошу перевірити роботу №5.
Дякую.

2023-02-08 16:58 UTC, Eastvarga requested changes
Є зауваження,
теку статики з аватарами краще додати до гітігнору та не зберігати їх у репозиторії

2023-02-08 16:58 UTC, Eastvarga commented on app.js
> +app.use("/api/avatars", avatarRouter);
Ви досі не уважні, отже Вам буде тяжко.
аватари повинні бути у ореолі юзерів за завданням
 тобто всередині рауту app.use("/api/users", authRouter);

2023-02-08 16:58 UTC, Eastvarga commented on controllers/filesController.js
> +const filesController = async (req, res) => {
не зрозумів навіщо пуста функція єдине призначення якої завжди відповідати успіх?

2023-02-08 16:58 UTC, Eastvarga commented on controllers/updateAvatar.js
> +  const [extention] = filename.split(".");
невірно, у модулі  path повинен бути метод для того щоб отримати розширення файлу
а якщо файл буде тест.іів.вів......івів.txt - що буде?

2023-02-08 16:58 UTC, Eastvarga commented on controllers/updateAvatar.js
> +    const avatarURL = path.join("avatars", avatarName);
співставте ті шляхи що генерує граватар, з тим що генеруєте Ви для юзера, та зрозумієте чому Ваш підхід дуже поганий
Чи маєте розуміння що таке URL шлях та що таке відносний шлях?

2023-02-08 16:58 UTC, Eastvarga commented on routes/api/avatar.js
> +router.use("/", express.static(FILE_DIR));
невірно,
Вам потрібно зробити статичною теку public і все, тим паче ця дія йде для усього сервера а отже юзати її треба у app
Тоді тека public стане кореневою текою для сервера, тобто увівши у строку браузера шлях
http://localhost:3000/avatars/63922ff5ba47e8f7c6d6d282_my%20photo%20mini.jpg
Ви отримаєте у відповідь цей файл якщо він буде знаходитись у файловій системі сервера за шляхом
public\avatars\63922ff5ba47e8f7c6d6d282_my%20photo%20mini.jpg
тобто **public =\= http://localhost:3000** стають еквівалентні, сподіваюсь так зрозуміліше

2023-02-10 12:48 UTC, StudentVlad5 commented on app.js
> +app.use("/api/avatars", avatarRouter);
в пункті 1 завдання визначено опис: 
Положи любое изображение в папку public/avatars и проверь что раздача статики работает. При переходе по такому URL браузер отобразит изображение.  http://localhost:<порт>/avatars/<имя файла с расширением>
- начебто для здачі ДЗ така умова лишається потрібною. розумію недоцільність, тому прибирав

2023-02-10 17:42 UTC, Eastvarga approved these changes
Невірна генерація URL шляху так і залишилась, хочете це ігнорувати, це Ваше право.

2023-02-10 17:42 UTC, Eastvarga commented on controllers/updateAvatar.js
> +    const avatarURL = path.join("avatars", avatarName);
Дуже погано, що Ви не розумієте різниці. Я не буду повторюватись, коли Ви не хочете вчитись

2023-02-10 17:42 UTC, merged